# Generated by Django 4.0.4 on 2022-05-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_category_lead_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="organisation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="leads.userprofile"),
            preserve_default=False,
        ),
    ]
